version: "2"

services:
  web:
    image: nginx:alpine
    volumes:
      - ./:/home/app
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
    environment:
      VIRTUAL_HOST: ${DOMAIN}
      LETSENCRYPT_HOST: ${DOMAIN}
      LETSENCRYPT_EMAIL: d.kochnov.optimus@gmail.com
    networks:
      - default
      - reverseproxy
    depends_on:
      - "app"
    restart: "no"
  
  app:
    image: 472532368511.dkr.ecr.us-east-1.amazonaws.com/budsies.com/backend/api/php/fpm:2022-05-30
    volumes:
      - ./:/home/app
    environment:
      - S3_CLIENT_REGION
      - S3_CLIENT_KEY
      - S3_CLIENT_SECRET
      - MAKERWARE_TOKEN
    restart: "no"
    networks:
      - default

networks:
    reverseproxy:
        name: webdevelopmentreverseproxy_default
